name: PKUMakers
favicon: null
layout_spectrum: 0.54591
typography_spectrum: 0.67029
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
